export const timezoneMapping = {
    "America/Aruba": "Aruba",
    "Asia/Kabul": "Afghanistan",
    "Africa/Luanda": "Angola",
    "America/Anguilla": "Anguilla",
    "Europe/Mariehamn": "Åland Islands",
    "Europe/Tirane": "Albania",
    "Europe/Andorra": "Andorra",
    "Asia/Dubai": "United Arab Emirates",
    "America/Argentina/Buenos_Aires": "Argentina",
    "America/Argentina/Cordoba": "Argentina",
    "America/Argentina/Salta": "Argentina",
    "America/Argentina/Jujuy": "Argentina",
    "America/Argentina/Tucuman": "Argentina",
    "America/Argentina/Catamarca": "Argentina",
    "America/Argentina/La_Rioja": "Argentina",
    "America/Argentina/San_Juan": "Argentina",
    "America/Argentina/Mendoza": "Argentina",
    "America/Argentina/San_Luis": "Argentina",
    "America/Argentina/Rio_Gallegos": "Argentina",
    "America/Argentina/Ushuaia": "Argentina",
    "Asia/Yerevan": "Armenia",
    "Pacific/Pago_Pago": "American Samoa",
    "Antarctica/McMurdo": "Antarctica",
    "Antarctica/Casey": "Antarctica",
    "Antarctica/Davis": "Antarctica",
    "Antarctica/DumontDUrville": "Antarctica",
    "Antarctica/Mawson": "Antarctica",
    "Antarctica/Palmer": "Antarctica",
    "Antarctica/Rothera": "Antarctica",
    "Antarctica/Syowa": "Antarctica",
    "Antarctica/Troll": "Antarctica",
    "Antarctica/Vostok": "Antarctica",
    "Indian/Kerguelen": "French Southern and Antarctic Lands",
    "America/Antigua": "Antigua and Barbuda",
    "Australia/Lord_Howe": "Australia",
    "Antarctica/Macquarie": "Australia",
    "Australia/Hobart": "Australia",
    "Australia/Currie": "Australia",
    "Australia/Melbourne": "Australia",
    "Australia/Sydney": "Australia",
    "Australia/Broken_Hill": "Australia",
    "Australia/Brisbane": "Australia",
    "Australia/Lindeman": "Australia",
    "Australia/Adelaide": "Australia",
    "Australia/Darwin": "Australia",
    "Australia/Perth": "Australia",
    "Australia/Eucla": "Australia",
    "Europe/Vienna": "Austria",
    "Asia/Baku": "Azerbaijan",
    "Africa/Bujumbura": "Burundi",
    "Europe/Brussels": "Belgium",
    "Africa/Porto-Novo": "Benin",
    "Africa/Ouagadougou": "Burkina Faso",
    "Asia/Dhaka": "Bangladesh",
    "Europe/Sofia": "Bulgaria",
    "Asia/Bahrain": "Bahrain",
    "America/Nassau": "Bahamas",
    "Europe/Sarajevo": "Bosnia and Herzegovina",
    "America/St_Barthelemy": "Saint Barthélemy",
    "Europe/Minsk": "Belarus",
    "America/Belize": "Belize",
    "Atlantic/Bermuda": "Bermuda",
    "America/La_Paz": "Bolivia",
    "America/Noronha": "Brazil",
    "America/Belem": "Brazil",
    "America/Fortaleza": "Brazil",
    "America/Recife": "Brazil",
    "America/Araguaina": "Brazil",
    "America/Maceio": "Brazil",
    "America/Bahia": "Brazil",
    "America/Sao_Paulo": "Brazil",
    "America/Campo_Grande": "Brazil",
    "America/Cuiaba": "Brazil",
    "America/Santarem": "Brazil",
    "America/Porto_Velho": "Brazil",
    "America/Boa_Vista": "Brazil",
    "America/Manaus": "Brazil",
    "America/Eirunepe": "Brazil",
    "America/Rio_Branco": "Brazil",
    "America/Barbados": "Barbados",
    "Asia/Brunei": "Brunei",
    "Asia/Thimphu": "Bhutan",
    "Europe/Oslo": "Norway",
    "Africa/Gaborone": "Botswana",
    "Africa/Bangui": "Central African Republic",
    "America/St_Johns": "Canada",
    "America/Halifax": "Canada",
    "America/Glace_Bay": "Canada",
    "America/Moncton": "Canada",
    "America/Goose_Bay": "Canada",
    "America/Blanc-Sablon": "Canada",
    "America/Toronto": "Canada",
    "America/Nipigon": "Canada",
    "America/Thunder_Bay": "Canada",
    "America/Iqaluit": "Canada",
    "America/Pangnirtung": "Canada",
    "America/Atikokan": "Canada",
    "America/Winnipeg": "Canada",
    "America/Rainy_River": "Canada",
    "America/Resolute": "Canada",
    "America/Rankin_Inlet": "Canada",
    "America/Regina": "Canada",
    "America/Swift_Current": "Canada",
    "America/Edmonton": "Canada",
    "America/Cambridge_Bay": "Canada",
    "America/Yellowknife": "Canada",
    "America/Inuvik": "Canada",
    "America/Creston": "Canada",
    "America/Dawson_Creek": "Canada",
    "America/Fort_Nelson": "Canada",
    "America/Vancouver": "Canada",
    "America/Whitehorse": "Canada",
    "America/Dawson": "Canada",
    "Indian/Cocos": "Cocos (Keeling) Islands",
    "Europe/Zurich": "Switzerland",
    "America/Santiago": "Chile",
    "Pacific/Easter": "Chile",
    "Asia/Shanghai": "China",
    "Asia/Urumqi": "China",
    "Africa/Abidjan": "Ivory Coast",
    "Africa/Douala": "Cameroon",
    "Africa/Kinshasa": "DR Congo",
    "Africa/Lubumbashi": "DR Congo",
    "Africa/Brazzaville": "Republic of the Congo",
    "Pacific/Rarotonga": "Cook Islands",
    "America/Bogota": "Colombia",
    "Indian/Comoro": "Comoros",
    "Atlantic/Cape_Verde": "Cape Verde",
    "America/Costa_Rica": "Costa Rica",
    "America/Havana": "Cuba",
    "America/Curacao": "Curaçao",
    "Indian/Christmas": "Christmas Island",
    "America/Cayman": "Cayman Islands",
    "Asia/Nicosia": "Cyprus",
    "Europe/Prague": "Czech Republic",
    "Europe/Berlin": "Germany",
    "Europe/Busingen": "Germany",
    "Africa/Djibouti": "Djibouti",
    "America/Dominica": "Dominica",
    "Europe/Copenhagen": "Denmark",
    "America/Santo_Domingo": "Dominican Republic",
    "Africa/Algiers": "Algeria",
    "America/Guayaquil": "Ecuador",
    "Pacific/Galapagos": "Ecuador",
    "Africa/Cairo": "Egypt",
    "Africa/Asmara": "Eritrea",
    "Africa/El_Aaiun": "Western Sahara",
    "Europe/Madrid": "Spain",
    "Africa/Ceuta": "Spain",
    "Atlantic/Canary": "Spain",
    "Europe/Tallinn": "Estonia",
    "Africa/Addis_Ababa": "Ethiopia",
    "Europe/Helsinki": "Finland",
    "Pacific/Fiji": "Fiji",
    "Atlantic/Stanley": "Falkland Islands",
    "Europe/Paris": "France",
    "Atlantic/Faroe": "Faroe Islands",
    "Pacific/Chuuk": "Micronesia",
    "Pacific/Pohnpei": "Micronesia",
    "Pacific/Kosrae": "Micronesia",
    "Africa/Libreville": "Gabon",
    "Europe/London": "United Kingdom",
    "Asia/Tbilisi": "Georgia",
    "Europe/Guernsey": "Guernsey",
    "Africa/Accra": "Ghana",
    "Europe/Gibraltar": "Gibraltar",
    "Africa/Conakry": "Guinea",
    "America/Guadeloupe": "Guadeloupe",
    "Africa/Banjul": "Gambia",
    "Africa/Bissau": "Guinea-Bissau",
    "Africa/Malabo": "Equatorial Guinea",
    "Europe/Athens": "Greece",
    "America/Grenada": "Grenada",
    "America/Godthab": "Greenland",
    "America/Danmarkshavn": "Greenland",
    "America/Scoresbysund": "Greenland",
    "America/Thule": "Greenland",
    "America/Guatemala": "Guatemala",
    "America/Cayenne": "French Guiana",
    "Pacific/Guam": "Guam",
    "America/Guyana": "Guyana",
    "Asia/Hong_Kong": "Hong Kong",
    "America/Tegucigalpa": "Honduras",
    "Europe/Zagreb": "Croatia",
    "America/Port-au-Prince": "Haiti",
    "Europe/Budapest": "Hungary",
    "Asia/Jakarta": "Indonesia",
    "Asia/Pontianak": "Indonesia",
    "Asia/Makassar": "Indonesia",
    "Asia/Jayapura": "Indonesia",
    "Europe/Isle_of_Man": "Isle of Man",
    "Asia/Kolkata": "India",
    "Indian/Chagos": "British Indian Ocean Territory",
    "Europe/Dublin": "Ireland",
    "Asia/Tehran": "Iran",
    "Asia/Baghdad": "Iraq",
    "Atlantic/Reykjavik": "Iceland",
    "Asia/Jerusalem": "Israel",
    "Europe/Rome": "Italy",
    "America/Jamaica": "Jamaica",
    "Europe/Jersey": "Jersey",
    "Asia/Amman": "Jordan",
    "Asia/Tokyo": "Japan",
    "Asia/Almaty": "Kazakhstan",
    "Asia/Qyzylorda": "Kazakhstan",
    "Asia/Aqtobe": "Kazakhstan",
    "Asia/Aqtau": "Kazakhstan",
    "Asia/Oral": "Kazakhstan",
    "Africa/Nairobi": "Kenya",
    "Asia/Bishkek": "Kyrgyzstan",
    "Asia/Phnom_Penh": "Cambodia",
    "Pacific/Tarawa": "Kiribati",
    "Pacific/Enderbury": "Kiribati",
    "Pacific/Kiritimati": "Kiribati",
    "America/St_Kitts": "Saint Kitts and Nevis",
    "Asia/Seoul": "South Korea",
    "Europe/Belgrade": "Serbia",
    "Asia/Kuwait": "Kuwait",
    "Asia/Vientiane": "Laos",
    "Asia/Beirut": "Lebanon",
    "Africa/Monrovia": "Liberia",
    "Africa/Tripoli": "Libya",
    "America/St_Lucia": "Saint Lucia",
    "Europe/Vaduz": "Liechtenstein",
    "Asia/Colombo": "Sri Lanka",
    "Africa/Maseru": "Lesotho",
    "Europe/Vilnius": "Lithuania",
    "Europe/Luxembourg": "Luxembourg",
    "Europe/Riga": "Latvia",
    "Asia/Macau": "Macau",
    "America/Marigot": "Saint Martin",
    "Africa/Casablanca": "Morocco",
    "Europe/Monaco": "Monaco",
    "Europe/Chisinau": "Moldova",
    "Indian/Antananarivo": "Madagascar",
    "Indian/Maldives": "Maldives",
    "America/Mexico_City": "Mexico",
    "America/Cancun": "Mexico",
    "America/Merida": "Mexico",
    "America/Monterrey": "Mexico",
    "America/Matamoros": "Mexico",
    "America/Mazatlan": "Mexico",
    "America/Chihuahua": "Mexico",
    "America/Ojinaga": "Mexico",
    "America/Hermosillo": "Mexico",
    "America/Tijuana": "Mexico",
    "America/Bahia_Banderas": "Mexico",
    "Pacific/Majuro": "Marshall Islands",
    "Pacific/Kwajalein": "Marshall Islands",
    "Europe/Skopje": "Macedonia",
    "Africa/Bamako": "Mali",
    "Europe/Malta": "Malta",
    "Asia/Rangoon": "Myanmar",
    "Europe/Podgorica": "Montenegro",
    "Asia/Ulaanbaatar": "Mongolia",
    "Asia/Hovd": "Mongolia",
    "Asia/Choibalsan": "Mongolia",
    "Pacific/Saipan": "Northern Mariana Islands",
    "Africa/Maputo": "Mozambique",
    "Africa/Nouakchott": "Mauritania",
    "America/Montserrat": "Montserrat",
    "America/Martinique": "Martinique",
    "Indian/Mauritius": "Mauritius",
    "Africa/Blantyre": "Malawi",
    "Asia/Kuala_Lumpur": "Malaysia",
    "Asia/Kuching": "Malaysia",
    "Indian/Mayotte": "Mayotte",
    "Africa/Windhoek": "Namibia",
    "Pacific/Noumea": "New Caledonia",
    "Africa/Niamey": "Niger",
    "Pacific/Norfolk": "Norfolk Island",
    "Africa/Lagos": "Nigeria",
    "America/Managua": "Nicaragua",
    "Pacific/Niue": "Niue",
    "Europe/Amsterdam": "Netherlands",
    "Asia/Kathmandu": "Nepal",
    "Pacific/Nauru": "Nauru",
    "Pacific/Auckland": "New Zealand",
    "Pacific/Chatham": "New Zealand",
    "Asia/Muscat": "Oman",
    "Asia/Karachi": "Pakistan",
    "America/Panama": "Panama",
    "Pacific/Pitcairn": "Pitcairn Islands",
    "America/Lima": "Peru",
    "Asia/Manila": "Philippines",
    "Pacific/Palau": "Palau",
    "Pacific/Port_Moresby": "Papua New Guinea",
    "Pacific/Bougainville": "Papua New Guinea",
    "Europe/Warsaw": "Poland",
    "America/Puerto_Rico": "Puerto Rico",
    "Asia/Pyongyang": "North Korea",
    "Europe/Lisbon": "Portugal",
    "Atlantic/Madeira": "Portugal",
    "Atlantic/Azores": "Portugal",
    "America/Asuncion": "Paraguay",
    "Asia/Gaza": "Palestine",
    "Asia/Hebron": "Palestine",
    "Pacific/Tahiti": "French Polynesia",
    "Pacific/Marquesas": "French Polynesia",
    "Pacific/Gambier": "French Polynesia",
    "Asia/Qatar": "Qatar",
    "Indian/Reunion": "Réunion",
    "Europe/Bucharest": "Romania",
    "Europe/Kaliningrad": "Russia",
    "Europe/Moscow": "Russia",
    "Europe/Simferopol": "Russia",
    "Europe/Volgograd": "Russia",
    "Europe/Kirov": "Russia",
    "Europe/Astrakhan": "Russia",
    "Europe/Samara": "Russia",
    "Europe/Ulyanovsk": "Russia",
    "Asia/Yekaterinburg": "Russia",
    "Asia/Omsk": "Russia",
    "Asia/Novosibirsk": "Russia",
    "Asia/Barnaul": "Russia",
    "Asia/Tomsk": "Russia",
    "Asia/Novokuznetsk": "Russia",
    "Asia/Krasnoyarsk": "Russia",
    "Asia/Irkutsk": "Russia",
    "Asia/Chita": "Russia",
    "Asia/Yakutsk": "Russia",
    "Asia/Khandyga": "Russia",
    "Asia/Vladivostok": "Russia",
    "Asia/Ust-Nera": "Russia",
    "Asia/Magadan": "Russia",
    "Asia/Sakhalin": "Russia",
    "Asia/Srednekolymsk": "Russia",
    "Asia/Kamchatka": "Russia",
    "Asia/Anadyr": "Russia",
    "Africa/Kigali": "Rwanda",
    "Asia/Riyadh": "Saudi Arabia",
    "Africa/Khartoum": "Sudan",
    "Africa/Dakar": "Senegal",
    "Asia/Singapore": "Singapore",
    "Atlantic/South_Georgia": "South Georgia",
    "Arctic/Longyearbyen": "Svalbard and Jan Mayen",
    "Pacific/Guadalcanal": "Solomon Islands",
    "Africa/Freetown": "Sierra Leone",
    "America/El_Salvador": "El Salvador",
    "Europe/San_Marino": "San Marino",
    "Africa/Mogadishu": "Somalia",
    "America/Miquelon": "Saint Pierre and Miquelon",
    "Africa/Juba": "South Sudan",
    "Africa/Sao_Tome": "São Tomé and Príncipe",
    "America/Paramaribo": "Suriname",
    "Europe/Bratislava": "Slovakia",
    "Europe/Ljubljana": "Slovenia",
    "Europe/Stockholm": "Sweden",
    "Africa/Mbabane": "Swaziland",
    "America/Lower_Princes": "Sint Maarten",
    "Indian/Mahe": "Seychelles",
    "Asia/Damascus": "Syria",
    "America/Grand_Turk": "Turks and Caicos Islands",
    "Africa/Ndjamena": "Chad",
    "Africa/Lome": "Togo",
    "Asia/Bangkok": "Thailand",
    "Asia/Dushanbe": "Tajikistan",
    "Pacific/Fakaofo": "Tokelau",
    "Asia/Ashgabat": "Turkmenistan",
    "Asia/Dili": "Timor-Leste",
    "Pacific/Tongatapu": "Tonga",
    "America/Port_of_Spain": "Trinidad and Tobago",
    "Africa/Tunis": "Tunisia",
    "Europe/Istanbul": "Turkey",
    "Pacific/Funafuti": "Tuvalu",
    "Asia/Taipei": "Taiwan",
    "Africa/Dar_es_Salaam": "Tanzania",
    "Africa/Kampala": "Uganda",
    "Europe/Kiev": "Ukraine",
    "Europe/Uzhgorod": "Ukraine",
    "Europe/Zaporozhye": "Ukraine",
    "Pacific/Johnston": "United States Minor Outlying Islands",
    "Pacific/Midway": "United States Minor Outlying Islands",
    "Pacific/Wake": "United States Minor Outlying Islands",
    "America/Montevideo": "Uruguay",
    "America/New_York": "United States",
    "America/Detroit": "United States",
    "America/Kentucky/Louisville": "United States",
    "America/Kentucky/Monticello": "United States",
    "America/Indiana/Indianapolis": "United States",
    "America/Indiana/Vincennes": "United States",
    "America/Indiana/Winamac": "United States",
    "America/Indiana/Marengo": "United States",
    "America/Indiana/Petersburg": "United States",
    "America/Indiana/Vevay": "United States",
    "America/Chicago": "United States",
    "America/Indiana/Tell_City": "United States",
    "America/Indiana/Knox": "United States",
    "America/Menominee": "United States",
    "America/North_Dakota/Center": "United States",
    "America/North_Dakota/New_Salem": "United States",
    "America/North_Dakota/Beulah": "United States",
    "America/Denver": "United States",
    "America/Boise": "United States",
    "America/Phoenix": "United States",
    "America/Los_Angeles": "United States",
    "America/Anchorage": "United States",
    "America/Juneau": "United States",
    "America/Sitka": "United States",
    "America/Metlakatla": "United States",
    "America/Yakutat": "United States",
    "America/Nome": "United States",
    "America/Adak": "United States",
    "Pacific/Honolulu": "United States",
    "Asia/Samarkand": "Uzbekistan",
    "Asia/Tashkent": "Uzbekistan",
    "Europe/Vatican": "Vatican City",
    "America/St_Vincent": "Saint Vincent and the Grenadines",
    "America/Caracas": "Venezuela",
    "America/Tortola": "British Virgin Islands",
    "America/St_Thomas": "United States Virgin Islands",
    "Asia/Ho_Chi_Minh": "Vietnam",
    "Pacific/Efate": "Vanuatu",
    "Pacific/Wallis": "Wallis and Futuna",
    "Pacific/Apia": "Samoa",
    "Asia/Aden": "Yemen",
    "Africa/Johannesburg": "South Africa",
    "Africa/Lusaka": "Zambia",
    "Africa/Harare": "Zimbabwe"
};

export const country_zoom = {
    "Afghanistan": 5,
    "Albania": 8,
    "Algeria": 4,
    "American Samoa": 9,
    "Andorra": 10,
    "Angola": 4,
    "Anguilla": 10,
    "Antarctica": 3,
    "Antigua and Barbuda": 10,
    "Argentina": 4,
    "Armenia": 8,
    "Aruba": 10,
    "Australia": 4,
    "Austria": 7,
    "Azerbaijan": 7,
    "Bahamas": 8,
    "Bahrain": 10,
    "Bangladesh": 6,
    "Barbados": 10,
    "Belarus": 6,
    "Belgium": 8,
    "Belize": 8,
    "Benin": 6,
    "Bermuda": 10,
    "Bhutan": 8,
    "Bolivia": 4,
    "Bosnia and Herzegovina": 7,
    "Botswana": 5,
    "Brazil": 4,
    "British Indian Ocean Territory": 4,
    "British Virgin Islands": 9,
    "Brunei": 9,
    "Bulgaria": 6,
    "Burkina Faso": 6,
    "Burundi": 8,
    "Cambodia": 6,
    "Cameroon": 6,
    "Canada": 4,
    "Cape Verde": 9,
    "Cayman Islands": 10,
    "Central African Republic": 5,
    "Chad": 4,
    "Chile": 5,
    "China": 4,
    "Christmas Island": 10,
    "Cocos (Keeling) Islands": 10,
    "Colombia": 4,
    "Comoros": 9,
    "Cook Islands": 10,
    "Costa Rica": 7,
    "Croatia": 7,
    "Cuba": 6,
    "Curaçao": 10,
    "Cyprus": 9,
    "Czech Republic": 7,
    "DR Congo": 4,
    "Denmark": 8,
    "Djibouti": 8,
    "Dominica": 10,
    "Dominican Republic": 8,
    "Ecuador": 6,
    "Egypt": 4,
    "El Salvador": 8,
    "Equatorial Guinea": 8,
    "Eritrea": 6,
    "Estonia": 8,
    "Ethiopia": 4,
    "Falkland Islands": 10,
    "Faroe Islands": 10,
    "Fiji": 8,
    "Finland": 6,
    "France": 5,
    "French Guiana": 10,
    "French Polynesia": 10,
    "French Southern and Antarctic Lands": 10,
    "Gabon": 6,
    "Gambia": 8,
    "Georgia": 7,
    "Germany": 6,
    "Ghana": 6,
    "Gibraltar": 10,
    "Greece": 6,
    "Greenland": 4,
    "Grenada": 10,
    "Guadeloupe": 10,
    "Guam": 10,
    "Guatemala": 6,
    "Guernsey": 10,
    "Guinea": 6,
    "Guinea-Bissau": 8,
    "Guyana": 6,
    "Haiti": 8,
    "Honduras": 6,
    "Hong Kong": 10,
    "Hungary": 7,
    "Iceland": 6,
    "India": 4,
    "Indonesia": 4,
    "Iran": 4,
    "Iraq": 6,
    "Ireland": 7,
    "Isle of Man": 10,
    "Israel": 8,
    "Italy": 6,
    "Ivory Coast": 6,
    "Jamaica": 8,
    "Japan": 6,
    "Jersey": 10,
    "Jordan": 7,
    "Kazakhstan": 4,
    "Kenya": 5,
    "Kiribati": 10,
    "Kuwait": 8,
    "Kyrgyzstan": 6,
    "Laos": 6,
    "Latvia": 7,
    "Lebanon": 8,
    "Lesotho": 8,
    "Liberia": 6,
    "Libya": 4,
    "Liechtenstein": 10,
    "Lithuania": 10,
    "Luxembourg": 10,
    "Macau": 10,
    "Macedonia": 8,
    "Madagascar": 5,
    "Malawi": 10,
    "Malaysia": 6,
    "Maldives": 10,
    "Mali": 4,
    "Malta": 10,
    "Marshall Islands": 10,
    "Martinique": 10,
    "Mauritania": 4,
    "Mauritius": 10,
    "Mayotte": 10,
    "Mexico": 4,
    "Micronesia": 10,
    "Moldova": 10,
    "Monaco": 10,
    "Mongolia": 4,
    "Montenegro": 10,
    "Montserrat": 10,
    "Morocco": 5,
    "Mozambique": 5,
    "Myanmar": 10,
    "Namibia": 5,
    "Nauru": 10,
    "Nepal": 6,
    "Netherlands": 8,
    "New Caledonia": 8,
    "New Zealand": 6,
    "Nicaragua": 6,
    "Niger": 4,
    "Nigeria": 5,
    "Niue": 10,
    "Norfolk Island": 10,
    "North Korea": 6,
    "Northern Mariana Islands": 10,
    "Norway": 6,
    "Oman": 6,
    "Pakistan": 5,
    "Palau": 10,
    "Palestine": 9,
    "Panama": 7,
    "Papua New Guinea": 6,
    "Paraguay": 6,
    "Peru": 4,
    "Philippines": 6,
    "Pitcairn Islands": 10,
    "Poland": 6,
    "Portugal": 7,
    "Puerto Rico": 10,
    "Qatar": 8,
    "Republic of the Congo": 6,
    "Romania": 6,
    "Russia": 3,
    "Rwanda": 10,
    "Réunion": 10,
    "Saint Barthélemy": 10,
    "Saint Kitts and Nevis": 10,
    "Saint Lucia": 10,
    "Saint Martin": 10,
    "Saint Pierre and Miquelon": 10,
    "Saint Vincent and the Grenadines": 10,
    "Samoa": 9,
    "San Marino": 10,
    "Saudi Arabia": 4,
    "Senegal": 6,
    "Serbia": 7,
    "Seychelles": 10,
    "Sierra Leone": 7,
    "Singapore": 10,
    "Sint Maarten": 10,
    "Slovakia": 8,
    "Slovenia": 8,
    "Solomon Islands": 8,
    "Somalia": 5,
    "South Africa": 4,
    "South Georgia": 9,
    "South Korea": 7,
    "South Sudan": 5,
    "Spain": 5,
    "Sri Lanka": 7,
    "Sudan": 4,
    "Suriname": 6,
    "Svalbard and Jan Mayen": 7,
    "Swaziland": 8,
    "Sweden": 6,
    "Switzerland": 8,
    "Syria": 6,
    "São Tomé and Príncipe": 10,
    "Taiwan": 8,
    "Tajikistan": 6,
    "Tanzania": 5,
    "Thailand": 5,
    "Timor-Leste": 8,
    "Togo": 7,
    "Tokelau": 10,
    "Tonga": 10,
    "Trinidad and Tobago": 9,
    "Tunisia": 6,
    "Turkey": 5,
    "Turkmenistan": 6,
    "Turks and Caicos Islands": 10,
    "Tuvalu": 10,
    "Uganda": 6,
    "Ukraine": 5,
    "United Arab Emirates": 7,
    "United Kingdom": 6,
    "United States": 4,
    "United States Minor Outlying Islands": 4,
    "United States Virgin Islands": 9,
    "Uruguay": 6,
    "Uzbekistan": 6,
    "Vanuatu": 8,
    "Vatican City": 10,
    "Venezuela": 5,
    "Vietnam": 6,
    "Wallis and Futuna": 10,
    "Western Sahara": 10,
    "Yemen": 5,
    "Zambia": 5,
    "Zimbabwe": 6,
    "Åland Islands": 10
  }

export const monatery_units = {
    "American Samoa": "USD",
    "Andorra": "EUR",
    "Japan": "JPY",
    "China": "CNY",
    "Australia": "AUD",
    "India": "INR",
    "Sri Lanka": "LKR",
    "Russia": "RUB",
    "Singapore": "SGD",
    "United Arab Emirates": "AED",
    "United Kingdom": "GBP",
    "Norway": "NOK",
    "Aruba": "AWG",
    "Afghanistan": "AFN",
    "Angola": "AOA",
    "Anguilla": "XCD",
    "Åland Islands": "EUR",
    "Albania": "ALL",
    "Argentina": "ARS",
    "Armenia": "AMD",
    "Antarctica": "AUD",
    "French Southern and Antarctic Lands": "EUR",
    "Antigua and Barbuda": "XCD",
    "Austria": "EUR",
    "Azerbaijan": "AZN",
    "Burundi": "BIF",
    "Belgium": "EUR",
    "Benin": "XOF",
    "Burkina Faso": "XOF",
    "Bangladesh": "BDT",
    "Bulgaria": "BGN",
    "Bahrain": "BHD",
    "Bahamas": "BSD",
    "Bosnia and Herzegovina": "BAM",
    "Saint Barthélemy": "EUR",
    "Belarus": "BYN",
    "Belize": "BZD",
    "Bermuda": "BMD",
    "Bolivia": "BOB",
    "Brazil": "BRL",
    "Barbados": "BBD",
    "Brunei": "BND",
    "Bhutan": "BTN",
    "Botswana": "BWP",
    "Central African Republic": "CDF",
    "Canada": "CAD",
    "Cocos (Keeling) Islands": "AUD",
    "Switzerland": "CHF",
    "Chile": "CLP",
    "Ivory Coast": "XOF",
    "Cameroon": "XAF",
    "DR Congo": "CDF",
    "Republic of the Congo": "CDF",
    "Cook Islands": "NZD",
    "Colombia": "COP",
    "Comoros": "KMF",
    "Cape Verde": "CVE",
    "Costa Rica": "CRC",
    "Cuba": "CUP",
    "Curaçao": "ANG",
    "Christmas Island": "AUD",
    "Cayman Islands": "KYD",
    "Cyprus": "EUR",
    "Czech Republic": "CZK",
    "Germany": "EUR",
    "Djibouti": "DJF",
    "Dominica": "XCD",
    "Denmark": "DKK",
    "Dominican Republic": "DOP",
    "Algeria": "DZD",
    "Ecuador": "USD",
    "Egypt": "EGP",
    "Eritrea": "ERN",
    "Western Sahara": "MAD",
    "Spain": "EUR",
    "Estonia": "EUR",
    "Ethiopia": "ETB",
    "Finland": "EUR",
    "Fiji": "FJD",
    "Falkland Islands": "FKP",
    "France": "EUR",
    "Faroe Islands": "DKK",
    "Micronesia": "USD",
    "Gabon": "XAF",
    "Georgia": "GEL",
    "Ghana": "GHS",
    "Gibraltar": "GIP",
    "Guinea": "GNF",
    "Guadeloupe": "EUR",
    "Gambia": "GMD",
    "Guinea-Bissau": "GNF",
    "Equatorial Guinea": "GNF",
    "Greece": "EUR",
    "Grenada": "XCD",
    "Greenland": "DKK",
    "Guatemala": "GTQ",
    "French Guiana": "EUR",
    "Guam": "USD",
    "Guyana": "GYD",
    "Hong Kong": "HKD",
    "Honduras": "HNL",
    "Croatia": "HRK",
    "Haiti": "HTG",
    "Hungary": "HUF",
    "Indonesia": "IDR",
    "Isle of Man": "GBP",
    "British Indian Ocean Territory": "USD",
    "Ireland": "EUR",
    "Iran": "IRR",
    "Iraq": "IQD",
    "Iceland": "ISK",
    "Israel": "ILS",
    "Italy": "EUR",
    "Jamaica": "JMD",
    "Jersey": "GBP",
    "Jordan": "JOD",
    "Kazakhstan": "KZT",
    "Kenya": "KES",
    "Kyrgyzstan": "KGS",
    "Cambodia": "KHR",
    "Kiribati": "AUD",
    "Saint Kitts and Nevis": "XCD",
    "South Korea": "KRW",
    "Serbia": "RSD",
    "Kuwait": "KWD",
    "Laos": "LAK",
    "Lebanon": "LBP",
    "Liberia": "LRD",
    "Libya": "LYD",
    "Saint Lucia": "XCD",
    "Liechtenstein": "CHF",
    "Lesotho": "LSL",
    "Lithuania": "EUR",
    "Luxembourg": "EUR",
    "Latvia": "EUR",
    "Macau": "MOP",
    "Saint Martin": "EUR",
    "Morocco": "MAD",
    "Monaco": "EUR",
    "Moldova": "MDL",
    "Madagascar": "MGA",
    "Maldives": "MVR",
    "Mexico": "MXN",
    "Marshall Islands": "USD",
    "Macedonia": "MKD",
    "Mali": "XAF",
    "Malta": "EUR",
    "Myanmar": "MMK",
    "Montenegro": "EUR",
    "Mongolia": "MNT",
    "Northern Mariana Islands": "USD",
    "Mozambique": "MZN",
    "Mauritania": "MRU",
    "Montserrat": "XCD",
    "Martinique": "EUR",
    "Mauritius": "MUR",
    "Malawi": "MWK",
    "Malaysia": "MYR",
    "Mayotte": "EUR",
    "Namibia": "NAD",
    "New Caledonia": "XPF",
    "Niger": "CDF",
    "Norfolk Island": "AUD",
    "Nigeria": "NGN",
    "Nicaragua": "NIO",
    "Niue": "NZD",
    "Netherlands": "EUR",
    "Nepal": "NPR",
    "Nauru": "AUD",
    "New Zealand": "NZD",
    "Oman": "OMR",
    "Pakistan": "PKR",
    "Panama": "PAB",
    "Pitcairn Islands": "NZD",
    "Peru": "PEN",
    "Philippines": "PHP",
    "Palau": "USD",
    "Papua New Guinea": "PGK",
    "Poland": "PLN",
    "Puerto Rico": "USD",
    "North Korea": "KPW",
    "Portugal": "EUR",
    "Paraguay": "PYG",
    "Palestine": "ILS",
    "French Polynesia": "XPF",
    "Qatar": "QAR",
    "Réunion": "EUR",
    "Romania": "RON",
    "Rwanda": "RWF",
    "Saudi Arabia": "SAR",
    "Sudan": "SDG",
    "Senegal": "XOF",
    "South Georgia": "GBP",
    "Svalbard and Jan Mayen": "NOK",
    "Solomon Islands": "SBD",
    "Sierra Leone": "SLL",
    "El Salvador": "SVC",
    "San Marino": "EUR",
    "Somalia": "SOS",
    "Saint Pierre and Miquelon": "EUR",
    "South Sudan": "SDG",
    "São Tomé and Príncipe": "STD",
    "Suriname": "SRD",
    "Slovakia": "EUR",
    "Slovenia": "EUR",
    "Sweden": "SEK",
    "Swaziland": "SZL",
    "Sint Maarten": "AWG",
    "Seychelles": "SCR",
    "Syria": "SYP",
    "Turks and Caicos Islands": "USD",
    "Chad": "CDF",
    "Togo": "CDF",
    "Thailand": "THB",
    "Tajikistan": "TJS",
    "Tokelau": "NZD",
    "Turkmenistan": "TMT",
    "Timor-Leste": "USD",
    "Tonga": "TOP",
    "Trinidad and Tobago": "TTD",
    "Tunisia": "TND",
    "Turkey": "TRY",
    "Tuvalu": "AUD",
    "Taiwan": "TWD",
    "Tanzania": "TZS",
    "Ukraine": "UAH",
    "Uganda": "UGX",
    "United States": "USD",
    "Uruguay": "UYU",
    "Uzbekistan": "UZS",
    "Vanuatu": "VUV",
    "Vatican City": "EUR",
    "Venezuela": "VES",
    "Vietnam": "VND",
    "Saint Vincent and the Grenadines": "XCD",
    "Wallis and Futuna": "XPF",
    "Samoa": "WST",
    "Yemen": "YER",
    "Zambia": "ZMW",
    "Zimbabwe": "ZWL",
    "Guernsey": "GBP",
    "United States Minor Outlying Islands": "USD",
    "British Virgin Islands": "XCD",
    "United States Virgin Islands": "USD",
    "South Africa": "ZAR"
}

export const country_codes = {
    "American Samoa": "AS",
    "Andorra": "AD",
    "Japan": "JP",
    "China": "CN",
    "Australia": "AU",
    "India": "IN",
    "Sri Lanka": "LK",
    "Russia": "RU",
    "Singapore": "SG",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "Norway": "NO",
    "Aruba": "AW",
    "Afghanistan": "AF",
    "Angola": "AO",
    "Anguilla": "AI",
    "Åland Islands": "AX",
    "Albania": "AL",
    "Argentina": "AR",
    "Armenia": "AM",
    "Antarctica": "AQ",
    "French Southern and Antarctic Lands": "TF",
    "Antigua and Barbuda": "AG",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Burundi": "BI",
    "Belgium": "BE",
    "Benin": "BJ",
    "Burkina Faso": "BF",
    "Bangladesh": "BD",
    "Bulgaria": "BG",
    "Bahrain": "BH",
    "Bahamas": "BS",
    "Bosnia and Herzegovina": "BA",
    "Saint Barthélemy": "BL",
    "Belarus": "BY",
    "Belize": "BZ",
    "Bermuda": "BM",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Barbados": "BB",
    "Brunei": "BN",
    "Bhutan": "BT",
    "Botswana": "BW",
    "Central African Republic": "CF",
    "Canada": "CA",
    "Cocos (Keeling) Islands": "CC",
    "Switzerland": "CH",
    "Chile": "CL",
    "Ivory Coast": "CI",
    "Cameroon": "CM",
    "DR Congo": "CD",
    "Republic of the Congo": "CG",
    "Cook Islands": "CK",
    "Colombia": "CO",
    "Comoros": "KM",
    "Cape Verde": "CV",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Christmas Island": "CX",
    "Cayman Islands": "KY",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Germany": "DE",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Denmark": "DK",
    "Dominican Republic": "DO",
    "Algeria": "DZ",
    "Ecuador": "EC",
    "Egypt": "EG",
    "Eritrea": "ER",
    "Western Sahara": "EH",
    "Spain": "ES",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Finland": "FI",
    "Fiji": "FJ",
    "Falkland Islands": "FK",
    "France": "FR",
    "Faroe Islands": "FO",
    "Micronesia": "FM",
    "Gabon": "GA",
    "Georgia": "GE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Guinea": "GN",
    "Guadeloupe": "GP",
    "Gambia": "GM",
    "Guinea-Bissau": "GW",
    "Equatorial Guinea": "GQ",
    "Greece": "GR",
    "Grenada": "GD",
    "Greenland": "GL",
    "Guatemala": "GT",
    "French Guiana": "GF",
    "Guam": "GU",
    "Guyana": "GY",
    "Hong Kong": "HK",
    "Honduras": "HN",
    "Croatia": "HR",
    "Haiti": "HT",
    "Hungary": "HU",
    "Indonesia": "ID",
    "Isle of Man": "IM",
    "British Indian Ocean Territory": "IO",
    "Ireland": "IE",
    "Iran": "IR",
    "Iraq": "IQ",
    "Iceland": "IS",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kyrgyzstan": "KG",
    "Cambodia": "KH",
    "Kiribati": "KI",
    "Saint Kitts and Nevis": "KN",
    "South Korea": "KR",
    "Serbia": "RS",
    "Kuwait": "KW",
    "Laos": "LA",
    "Lebanon": "LB",
    "Liberia": "LR",
    "Libya": "LY",
    "Saint Lucia": "LC",
    "Liechtenstein": "LI",
    "Lesotho": "LS",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Latvia": "LV",
    "Macau": "MO",
    "Saint Martin": "MF",
    "Morocco": "MA",
    "Monaco": "MC",
    "Moldova": "MD",
    "Madagascar": "MG",
    "Maldives": "MV",
    "Mexico": "MX",
    "Marshall Islands": "MH",
    "Macedonia": "MK",
    "Mali": "ML",
    "Malta": "MT",
    "Myanmar": "MM",
    "Montenegro": "ME",
    "Mongolia": "MN",
    "Northern Mariana Islands": "MP",
    "Mozambique": "MZ",
    "Mauritania": "MR",
    "Montserrat": "MS",
    "Martinique": "MQ",
    "Mauritius": "MU",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Mayotte": "YT",
    "Namibia": "NA",
    "New Caledonia": "NC",
    "Niger": "NE",
    "Norfolk Island": "NF",
    "Nigeria": "NG",
    "Nicaragua": "NI",
    "Niue": "NU",
    "Netherlands": "NL",
    "Nepal": "NP",
    "Nauru": "NR",
    "New Zealand": "NZ",
    "Oman": "OM",
    "Pakistan": "PK",
    "Panama": "PA",
    "Pitcairn Islands": "PN",
    "Peru": "PE",
    "Philippines": "PH",
    "Palau": "PW",
    "Papua New Guinea": "PG",
    "Poland": "PL",
    "Puerto Rico": "PR",
    "North Korea": "KP",
    "Portugal": "PT",
    "Paraguay": "PY",
    "Palestine": "PS",
    "French Polynesia": "PF",
    "Qatar": "QA",
    "Réunion": "RE",
    "Romania": "RO",
    "Rwanda": "RW",
    "Saudi Arabia": "SA",
    "Sudan": "SD",
    "Senegal": "SN",
    "South Georgia": "GS",
    "Svalbard and Jan Mayen": "SJ",
    "Solomon Islands": "SB",
    "Sierra Leone": "SL",
    "El Salvador": "SV",
    "San Marino": "SM",
    "Somalia": "SO",
    "Saint Pierre and Miquelon": "PM",
    "South Sudan": "SS",
    "São Tomé and Príncipe": "ST",
    "Suriname": "SR",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Sweden": "SE",
    "Swaziland": "SZ",
    "Sint Maarten": "SX",
    "Seychelles": "SC",
    "Syria": "SY",
    "Turks and Caicos Islands": "TC",
    "Chad": "TD",
    "Togo": "TG",
    "Thailand": "TH",
    "Tajikistan": "TJ",
    "Tokelau": "TK",
    "Turkmenistan": "TM",
    "Timor-Leste": "TL",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Tuvalu": "TV",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "Ukraine": "UA",
    "Uganda": "UG",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatican City": "VA",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Saint Vincent and the Grenadines": "VC",
    "Wallis and Futuna": "WF",
    "Samoa": "WS",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
    "Guernsey": "GG",
    "United States Minor Outlying Islands": "UM",
    "British Virgin Islands": "VG",
    "United States Virgin Islands": "VI",
    "South Africa": "ZA"
    }

export const country_flags = {
    'Micronesia': '🇲🇭', 'Ecuador': '🇪🇨', 'Iran': '🇮🇷', 'Thailand': '🇹🇭', 'Macau': '🇲🇴',
    'Togo': '🇹🇬', 'Papua New Guinea': '🇵🇬', 'Hong Kong': '🇭🇰', 'Kazakhstan': '🇰🇿', 'Haiti': '🇭🇹',
    'South Africa': '🇿🇦', 'Timor-Leste': '🇹🇱', 'Saint Kitts and Nevis': '🇰🇳', 'Romania': '🇷🇴', 'Macedonia': '🇲🇰',
    'Bahamas': '🇧🇸', 'Hungary': '🇭🇺', 'Burkina Faso': '🇧🇫', 'Singapore': '🇸🇬', 'Nigeria': '🇳🇬',
    'Svalbard and Jan Mayen': '🇸🇯', 'Malaysia': '🇲🇾', 'India': '🇮🇳', 'Sudan': '🇸🇩', 'Bosnia and Herzegovina': '🇧🇦',
    'Bermuda': '🇧🇲', 'Kyrgyzstan': '🇰🇬', 'Madagascar': '🇲🇬', 'Martinique': '🇲🇶', 'Venezuela': '🇻🇪',
    'Poland': '🇵🇱', 'Republic of the Congo': '🇨🇬', 'Mexico': '🇲🇽', 'Puerto Rico': '🇵🇷', 'Saint Vincent and the Grenadines': '🇻🇨',
    'Barbados': '🇧🇧', 'Niue': '🇳🇺', 'Netherlands': '🇳🇱', 'Egypt': '🇪🇬', 'Faroe Islands': '🇫🇴',
    'Jamaica': '🇯🇲', 'Ivory Coast': '🇮🇪', 'Bangladesh': '🇧🇩', 'Switzerland': '🇨🇭', 'Montserrat': '🇲🇸',
    'Rwanda': '🇷🇼', 'Saudi Arabia': '🇸🇦', 'Costa Rica': '🇨🇷', 'Bahrain': '🇧🇭', 'Mayotte': '🇾🇹',
    'Malta': '🇲🇹', 'Denmark': '🇩🇰', 'Libya': '🇱🇾', 'Åland Islands': '🏝', 'Cook Islands': '🇨🇰',
    'Aruba': '🇦🇼', 'Vatican City': '🇻🇦', 'Guam': '🇬🇺', 'Sint Maarten': '🇸🇽', 'Ukraine': '🇺🇦',
    'Wallis and Futuna': '🇼🇫', 'United Arab Emirates': '🇦🇪', 'Guatemala': '🇬🇹', 'Cyprus': '🇨🇾', 'Turkmenistan': '🇹🇲',
    'Norfolk Island': '🇳🇫', 'Kuwait': '🇰🇼', 'Taiwan': '🇹🇼', 'United States': '🇺🇸', 'Sierra Leone': '🇸🇱',
    'United States Minor Outlying Islands': '🇺🇸', 'French Southern and Antarctic Lands': '🇫🇷', 'Spain': '🇪🇸', 'Latvia': '🇱🇻',
    'Qatar': '🇶🇦', 'Dominica': '🇩🇲', 'Zambia': '🇿🇲', 'Mozambique': '🇲🇿', 'Namibia': '🇳🇦', 'Czech Republic': '🇨🇿',
    'Niger': '🇳🇪', 'Syria': '🇸🇾', 'Tokelau': '🇹🇰', 'DR Congo': '🇩🇴', 'Guyana': '🇬🇾', 'Marshall Islands': '🇲🇭',
    'American Samoa': '🇦🇸', 'Eritrea': '🇪🇷', 'Grenada': '🇬🇩', 'Guinea': '🇬🇳', 'Kiribati': '🇰🇮', 'Pitcairn Islands': '🇵🇬',
    'Norway': '🇳🇴', 'Mauritania': '🇲🇷', 'San Marino': '🇸🇲', 'Samoa': '🇸🇧', 'Laos': '🇱🇦', 'Chile': '🇨🇱',
    'South Korea': '🇰🇷', 'Azerbaijan': '🇦🇿', 'Antigua and Barbuda': '🇦🇬', 'Cayman Islands': '🇰🇾', 'Guadeloupe': '🇬🇵',
    'Cameroon': '🇨🇲', 'Mali': '🇲🇱', 'Malawi': '🇲🇼', 'Sweden': '🇸🇪', 'China': '🇨🇳', 'Tanzania': '🇹🇿',
    'Falkland Islands': '🇫🇰', 'Saint Lucia': '🇱🇨', 'New Caledonia': '🇳🇨', 'Pakistan': '🇵🇰', 'Finland': '🇫🇮',
    'Bhutan': '🇧🇹', 'Bulgaria': '🇧🇬', 'Zimbabwe': '🇿🇼', 'Tonga': '🇹🇴', 'Serbia': '🇷🇸', 'Fiji': '🇫🇯',
    'Guinea-Bissau': '🇬🇼', 'Nepal': '🇳🇵', 'El Salvador': '🇸🇻', 'Croatia': '🇭🇷', 'Paraguay': '🇵🇾', 'Iraq': '🇮🇶',
    'Antarctica': '🏔', 'Solomon Islands': '🇸🇧', 'South Sudan': '🇸🇸', 'Indonesia': '🇮🇩', 'Liechtenstein': '🇱🇮',
    'Anguilla': '🇦🇮', 'Nicaragua': '🇳🇮', 'Russia': '🇷🇺', 'Gambia': '🇬🇲', 'South Georgia': '🇬🇸', 'Senegal': '🇸🇳',
    'Algeria': '🇩🇿', 'Germany': '🇩🇪', 'Belgium': '🇧🇪', 'Bolivia': '🇧🇴', 'Brazil': '🇧🇷', 'Equatorial Guinea': '🇬🇶',
    'Seychelles': '🇸🇨', 'Philippines': '🇵🇭', 'Estonia': '🇪🇪', 'Swaziland': '🇸🇿', 'Gabon': '🇬🇦', 'Western Sahara': '🇪🇭',
    'British Indian Ocean Territory': '🇮🇴', 'Belize': '🇧🇿', 'Cocos (Keeling) Islands': '🇰🇭', 'Jersey': '🇯🇪',
    'Brunei': '🇧🇳', 'Burundi': '🇧🇮', 'Gibraltar': '🇬🇮', 'Curaçao': '🇨🇼', 'São Tomé and Príncipe': '🇸🇹',
    'Honduras': '🇭🇳', 'Greenland': '🇬🇱', 'Tunisia': '🇹🇳', 'Argentina': '🇦🇷', 'Jordan': '🇯🇴', 'Turkey': '🇹🇷',
    'Vanuatu': '🇻🇺', 'North Korea': '🇰🇵', 'Albania': '🇦🇱', 'Botswana': '🇧🇼', 'Saint Martin': '🇲🇸', 'Djibouti': '🇩🇯',
    'Mongolia': '🇲🇳', 'Armenia': '🇦🇲', 'Georgia': '🇬🇪', 'Italy': '🇮🇹', 'Benin': '🇧🇯', 'Kenya': '🇰🇪',
    'Palau': '🇵🇼', 'Slovenia': '🇸🇮', 'Uruguay': '🇺🇾', 'Japan': '🇯🇵', 'Liberia': '🇱🇷', 'Cuba': '🇨🇺',
    'Ghana': '🇬🇭', 'Palestine': '🇵🇸', 'Saint Pierre and Miquelon': '🇵🇲', 'Vietnam': '🇻🇳', 'United Kingdom': '🇬🇧',
    'Andorra': '🇦🇩', 'Greece': '🇬🇷', 'French Guiana': '🇬🇫', 'Northern Mariana Islands': '🇲🇺', 'Morocco': '🇲🇦',
    'New Zealand': '🇳🇿', 'Tajikistan': '🇹🇯', 'Christmas Island': '🇨🇽', 'Yemen': '🇾🇴', 'Chad': '🇹🇩',
    'Colombia': '🇨🇴', 'Somalia': '🇸🇴', 'Oman': '🇴🇲', 'United States Virgin Islands': '🇻🇮', 'Central African Republic': '🇨🇫',
    'Saint Barthélemy': '🇧🇱', 'Lebanon': '🇱🇧', 'Turks and Caicos Islands': '🇹🇰', 'Uzbekistan': '🇺🇿',
    'Nauru': '🇳🇷', 'Suriname': '🇸🇷', 'Ethiopia': '🇪🇹', 'Iceland': '🇮🇸', 'Afghanistan': '🇦🇫', 'Austria': '🇦🇹',
    'Lithuania': '🇱🇹', 'Portugal': '🇵🇹', 'Montenegro': '🇲🇪', 'Dominican Republic': '🇩🇴', 'Isle of Man': '🇮🇲',
    'British Virgin Islands': '🇻🇬', 'Réunion': '🇷🇪', 'Uganda': '🇺🇬', 'Peru': '🇵🇪', 'French Polynesia': '🇵🇫',
    'Lesotho': '🇱🇸', 'Trinidad and Tobago': '🇹🇹', 'Australia': '🇦🇺', 'Luxembourg': '🇱🇺', 'Tuvalu': '🇹🇻',
    'Guernsey': '🇬🇬', 'Myanmar': '🇲🇲', 'Canada': '🇨🇦', 'Israel': '🇮🇱', 'Monaco': '🇲🇨', 'Comoros': '🇰🇲',
    'Ireland': '🇮🇪', 'Cape Verde': '🇨🇻', 'France': '🇫🇷', 'Angola': '🇦🇴', 'Sri Lanka': '🇱🇰', 'Moldova': '🇲🇩',
    'Belarus': '🇧🇾', 'Cambodia': '🇰🇭', 'Mauritius': '🇲🇺', 'Maldives': '🇲🇻', 'Panama': '🇵🇦', 'Slovakia': '🇸🇰'
}

export const monetary_units_flags = {
    "USD": "🇺🇸", // American Samoa, Ecuador, Guam, Marshall Islands, Puerto Rico, Timor-Leste, United States, United States Minor Outlying Islands, Western Sahara, Turks and Caicos Islands
    "EUR": "🇪🇺", // Andorra, Åland Islands, France, Belgium, Spain, Estonia, Finland, Ireland, Cyprus, Germany, Netherlands, Luxembourg, Latvia, Lithuania, Monaco, Malta, Portugal, Slovakia, Slovenia, San Marino, Réunion, Romania, Moldova, Greece, Montenegro, Kosovo, Vatican City
    "JPY": "🇯🇵", // Japan
    "CNY": "🇨🇳", // China
    "AUD": "🇦🇺", // Australia, Antarctica, Cocos Islands, Kiribati, Christmas Island, Norfolk Island, Nauru, New Zealand, Tokelau, Tuvalu
    "INR": "🇮🇳", // India
    "LKR": "🇱🇰", // Sri Lanka
    "RUB": "🇷🇺", // Russia
    "SGD": "🇸🇬", // Singapore
    "AED": "🇦🇪", // United Arab Emirates
    "GBP": "🇬🇧", // United Kingdom, Isle of Man, Jersey, Gibraltar, South Georgia, Saint Helena
    "NOK": "🇳🇴", // Norway, Svalbard and Jan Mayen
    "AWG": "🇦🇼", // Aruba
    "AFN": "🇦🇫", // Afghanistan
    "AOA": "🇦🇴", // Angola
    "XCD": "🇬🇩", // Anguilla, Antigua and Barbuda, Grenada, Saint Kitts and Nevis, Saint Lucia, Saint Pierre and Miquelon, Saint Vincent and the Grenadines, Montserrat, British Virgin Islands
    "ALL": "🇦🇱", // Albania
    "ARS": "🇦🇷", // Argentina
    "AMD": "🇦🇲", // Armenia
    "BIF": "🇧🇮", // Burundi
    "BZD": "🇧🇿", // Belize
    "BMD": "🇧🇲", // Bermuda
    "BOB": "🇧🇴", // Bolivia
    "BRL": "🇧🇷", // Brazil
    "BBD": "🇧🇧", // Barbados
    "BND": "🇧🇳", // Brunei
    "BTN": "🇧🇹", // Bhutan
    "BWP": "🇧🇼", // Botswana
    "CDF": "🇨🇩", // Central African Republic, Democratic Republic of the Congo, Republic of the Congo, Niger, Chad, Togo
    "CAD": "🇨🇦", // Canada
    "CHF": "🇨🇭", // Switzerland, Liechtenstein
    "CLP": "🇨🇱", // Chile
    "KMF": "🇰🇲", // Comoros
    "CVE": "🇨🇻", // Cape Verde
    "CRC": "🇨🇷", // Costa Rica
    "CUP": "🇨🇺", // Cuba
    "ANG": "🇧🇶", // Curaçao
    "KYD": "🇰🇾", // Cayman Islands
    "DKK": "🇩🇰", // Denmark, Faroe Islands, Greenland
    "DOP": "🇩🇴", // Dominican Republic
    "DZD": "🇩🇿", // Algeria
    "EGP": "🇪🇬", // Egypt
    "ERN": "🇪🇷", // Eritrea
    "ETB": "🇪🇹", // Ethiopia
    "FJD": "🇫🇯", // Fiji
    "Falkland Islands": "🇫🇰", // Falkland Islands
    "GEL": "🇬🇪", // Georgia
    "GHS": "🇬🇭", // Ghana
    "GIP": "🇬🇮", // Gibraltar
    "GNF": "🇬🇳", // Guinea, Guinea-Bissau, Equatorial Guinea
    "GMD": "🇬🇲", // Gambia
    "GTQ": "🇬🇹", // Guatemala
    "GYD": "🇬🇾", // Guyana
    "HKD": "🇭🇰", // Hong Kong
    "HNL": "🇭🇳", // Honduras
    "HRK": "🇭🇷", // Croatia
    "HTG": "🇭🇹", // Haiti
    "HUF": "🇭🇺", // Hungary
    "IDR": "🇮🇩", // Indonesia
    "ILS": "🇮🇱", // Israel
    "ISK": "🇮🇸", // Iceland
    "JMD": "🇯🇲", // Jamaica
    "KGS": "🇰🇬", // Kyrgyzstan
    "KHR": "🇰🇭", // Cambodia
    "KRW": "🇰🇷", // South Korea
    "KWD": "🇰🇼", // Kuwait
    "LAK": "🇱🇦", // Laos
    "LBP": "🇱🇧", // Lebanon
    "LRD": "🇱🇷", // Liberia
    "LYD": "🇱🇾", // Libya
    "LSL": "🇱🇸", // Lesotho
    "MDL": "🇲🇩", // Moldova
    "MGA": "🇲🇬", // Madagascar
    "MVR": "🇲🇻", // Maldives
    "MXN": "🇲🇽", // Mexico
    "MMK": "🇲🇲", // Myanmar
    "MNT": "🇲🇳", // Mongolia
    "MZN": "🇲🇿", // Mozambique
    "MRU": "🇲🇷", // Mauritania
    "MUR": "🇲🇺", // Mauritius
    "MWK": "🇲🇼", // Malawi
    "MYR": "🇲🇾", // Malaysia
    "NAD": "🇳🇦", // Namibia
    "NGN": "🇳🇬", // Nigeria
    "NIO": "🇳🇮", // Nicaragua
    "NZD": "🇳🇿", // New Zealand, Pitcairn Islands, Niue, Tokelau
    "OMR": "🇴🇲", // Oman
    "PKR": "🇵🇰", // Pakistan
    "PAB": "🇵🇦", // Panama
    "PHP": "🇵🇭", // Philippines
    "PLN": "🇵🇱", // Poland
    "PEN": "🇵🇪", // Peru
    "QAR": "🇶🇦", // Qatar
    "RON": "🇷🇴", // Romania
    "RWF": "🇷🇼", // Rwanda
    "SAR": "🇸🇦", // Saudi Arabia
    "SDG": "🇸🇩", // Sudan, South Sudan
    "SEK": "🇸🇪", // Sweden
    "SZL": "🇸🇿", // Swaziland
    "SYP": "🇸🇾", // Syria
    "THB": "🇹🇭", // Thailand
    "TJS": "🇹🇯", // Tajikistan
    "TMT": "🇹🇲", // Turkmenistan
    "TOP": "🇹🇴", // Tonga
    "TTD": "🇹🇹", // Trinidad and Tobago
    "TND": "🇹🇳", // Tunisia
    "TRY": "🇹🇷", // Turkey
    "TVD": "🇹🇻", // Tuvalu
    "TWD": "🇹🇼", // Taiwan
    "TZS": "🇹🇿", // Tanzania
    "UAH": "🇺🇦", // Ukraine
    "UGX": "🇺🇬", // Uganda
    "UYU": "🇺🇾", // Uruguay
    "UZS": "🇺🇿", // Uzbekistan
    "VUV": "🇻🇺", // Vanuatu
    "VES": "🇻🇪", // Venezuela
    "VND": "🇻🇳", // Vietnam
    "WST": "🇼🇸", // Samoa
    "YER": "🇾🇪", // Yemen
    "ZMW": "🇿🇲", // Zambia
    "ZWL": "🇿🇼", // Zimbabwe
    "ZAR": "🇿🇦", // South Africa
};

export const getCountryFromTimezone = () => {
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return timezoneMapping[timezone] || 'Unknown';
};

export const getMonateryUnitFromCountry = () => {
    const country = getCountryFromTimezone();
    return monatery_units[country] || 'USD';
};

export const getCountryZoom = (country) => {
    return country_zoom[country] || 4;
};

// Format currency
export const formatCurrency = (amount, currency) => {
    return new Intl.NumberFormat('en-US', { 
      style: 'currency', 
      currency: currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(Math.ceil(amount));
  };